# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.6.0'
    pod 'RxCocoa', '6.6.0'
    pod 'SnapKit', '~> 5.7.0'
  # Pods for weather

end
